/**
 * @redbusagent/shared — Protocol Types
 *
 * Defines the contract for all WebSocket messages exchanged between
 * the Daemon (server) and TUI (client). Every message must conform
 * to a discriminated union keyed on `type`.
 */

// ─── Base Envelope ────────────────────────────────────────────────

export interface BaseMessage {
    /** ISO-8601 timestamp of when the message was created */
    readonly timestamp: string;
}

// ─── Server → Client Messages ─────────────────────────────────────

export interface HeartbeatMessage extends BaseMessage {
    readonly type: 'heartbeat';
    readonly payload: {
        readonly uptimeMs: number;
        readonly pid: number;
        readonly port: number;
    };
}

export interface LogMessage extends BaseMessage {
    readonly type: 'log';
    readonly payload: {
        readonly level: 'info' | 'warn' | 'error' | 'debug';
        readonly source: string;
        readonly message: string;
    };
}

export interface SystemStatusMessage extends BaseMessage {
    readonly type: 'system:status';
    readonly payload: {
        readonly status: 'starting' | 'ready' | 'shutting_down';
    };
}

/** A chunk of streamed text from the LLM response */
export interface ChatStreamChunkMessage extends BaseMessage {
    readonly type: 'chat:stream:chunk';
    readonly payload: {
        /** Unique ID for this conversation turn */
        readonly requestId: string;
        /** The text delta (partial token) */
        readonly delta: string;
    };
}

/** Signals the end of a streaming response */
export interface ChatStreamDoneMessage extends BaseMessage {
    readonly type: 'chat:stream:done';
    readonly payload: {
        readonly requestId: string;
        /** Full accumulated response text */
        readonly fullText: string;
        /** Which tier handled this request */
        readonly tier: 'tier1' | 'tier2';
        /** Model identifier used */
        readonly model: string;
    };
}

/** Signals an error during chat processing */
export interface ChatErrorMessage extends BaseMessage {
    readonly type: 'chat:error';
    readonly payload: {
        readonly requestId: string;
        readonly error: string;
    };
}

/** The LLM decided to call a tool (Forge action) */
export interface ChatToolCallMessage extends BaseMessage {
    readonly type: 'chat:tool:call';
    readonly payload: {
        readonly requestId: string;
        readonly toolName: string;
        readonly args: Record<string, unknown>;
    };
}

/** A tool execution completed */
export interface ChatToolResultMessage extends BaseMessage {
    readonly type: 'chat:tool:result';
    readonly payload: {
        readonly requestId: string;
        readonly toolName: string;
        readonly success: boolean;
        readonly result: string;
    };
}

// ─── Proactive Messages (Heartbeat extensions) ──────────────────────

export interface ProactiveThoughtMessage extends BaseMessage {
    readonly type: 'proactive:thought';
    readonly payload: {
        readonly text: string;
        readonly status: 'thinking' | 'action' | 'done';
    };
}

export interface SystemAlertMessage extends BaseMessage {
    readonly type: 'system:alert';
    readonly payload: {
        readonly id: string;
        readonly message: string;
    };
}

// ─── Client → Server Messages ─────────────────────────────────────

export interface PingMessage extends BaseMessage {
    readonly type: 'ping';
}

/** User sends a chat message to the daemon for LLM processing */
export interface ChatRequestMessage extends BaseMessage {
    readonly type: 'chat:request';
    readonly payload: {
        /** Unique ID for this request (generated by client) */
        readonly requestId: string;
        /** The user's message text */
        readonly content: string;
        /** Optional: force a specific tier */
        readonly tier?: 'tier1' | 'tier2';
        /** Optional: flag for persona onboarding */
        readonly isOnboarding?: boolean;
        /** Unified conversational history array from the frontend */
        readonly messages?: any[];
    };
}


/** User selects a command from the slash palette */
export interface SystemCommandMessage extends BaseMessage {
    readonly type: 'system:command';
    readonly payload: {
        readonly command: 'force-local' | 'auto-route' | 'switch-cloud' | 'status' | 'set-default-tier';
        readonly args?: Record<string, unknown>;
    };
}

// ─── Discriminated Unions ─────────────────────────────────────────

export type DaemonMessage =
    | HeartbeatMessage
    | LogMessage
    | SystemStatusMessage
    | ChatStreamChunkMessage
    | ChatStreamDoneMessage
    | ChatErrorMessage
    | ChatToolCallMessage
    | ChatToolResultMessage
    | ProactiveThoughtMessage
    | SystemAlertMessage;

export type ClientMessage =
    | PingMessage
    | ChatRequestMessage
    | SystemCommandMessage;

/** All possible message types flowing through the WebSocket */
export type ProtocolMessage = DaemonMessage | ClientMessage;

/** Extracts the `type` literal from a message union */
export type MessageType = ProtocolMessage['type'];
